### ISSUE TITLE
FR: Remove braces automatically

### ISSUE THREAD

**Issue by mayurankv** [RyotaUshio/obsidian-inline-math#3]
It would be great if there was some functionality to remove braces automatically.

I would implement this as to clean brackets from the previous inline math environment when:

- there is no spaces between the braces and a non-space character on both sides of the previous inline math
- and when a new inline math environment is entered

I appreciate this plugin loads but I hate the idea that I'm littering braces everywhere throughout my vault which would be annoying if I ever switch away from Obsidian.

Thanks so much for this plugin!

**Comment by RyotaUshio** [comment]
Released as [0.3.0](https://github.com/RyotaUshio/obsidian-inline-math/releases/tag/0.3.0)!

**Comment by mayurankv** [comment]
Thanks so much, an amazing plug-in!
