### ISSUE TITLE
Yet another Latex Suite imcompatiblity issue

### ISSUE THREAD

**Issue by RyotaUshio** [RyotaUshio/obsidian-inline-math#6]
https://github.com/RyotaUshio/obsidian-inline-math/assets/72342591/17f4768c-0da5-4666-b851-6ff46205909f

**Comment by carpetdev** [comment]
It seems like this is fixed by changing the latex suite auto bracket pairing snippet from

```{trigger: "(", replacement: "($0)$1", options: "mA"}```
to
```{trigger: "(", replacement: "($0)", options: "mA"}```

This doesn't seem to affect tabbing out of the brackets, so the tabstop $1 wasn't needed in the first place.

**Comment by RyotaUshio** [comment]
@carpetdev You are absolutely right... I never imagined the solution was this simple!
Thank you a ton for the insight, I will add some note about this in readme.

**Comment by carpetdev** [comment]
No worries. I'm glad the fix ended up being easy too. Thanks for your work on all your plugins - they've massively improved my note-taking!
