### ISSUE TITLE
Incompatibility with Vim keybinds

### ISSUE THREAD

**Issue by KellyNyanbinary** [RyotaUshio/obsidian-inline-math#7]
When using `h` and `l` in Vim mode to move the cursor left and right, the braces before and after `$` are not treated as one character with the `$`, resulting in having to move the cursor multiple times to go over both braces and the `$`.

**Comment by RyotaUshio** [comment]
Unfortunately, that is unlikely to be something that I can control because it's an upstream bug of Obsidian's vim emulator. It's getting better a little by little but there are still some serious problems

**Comment by KellyNyanbinary** [comment]
See [above](https://github.com/RyotaUshio/obsidian-inline-math/issues/7#issuecomment-1966242944).

**Comment by KellyNyanbinary** [comment]
See [above](https://github.com/RyotaUshio/obsidian-inline-math/issues/7#issuecomment-1966242944).

**Comment by RyotaUshio** [comment]
What?

**Comment by KellyNyanbinary** [comment]
If the bug is with Obsidian's Vim mode, leaving the issue open here won't be useful, so I closed it with the reason stated by you.
