### ISSUE TITLE
Feature: working inside a code-blocks

### ISSUE THREAD

**Issue by muhammadbabaev** [RyotaUshio/obsidian-inline-math#8]
It would be better if the plugin could work inside code blocks (maybe specified in some settings field).
For example, now I use the Tabs plugin, which adds special code blocks starting with `~~~tabs` or ` ```tabs`.
Inside which I write math blocks (`$ $`, `$$ $$`).
But in this case the plugin doesn't work.

![Screenshot from 2024-10-27 22-40-29](https://github.com/user-attachments/assets/5a05e7b1-ecc0-4f82-adbe-ee19848cc4ff)

**Comment by RyotaUshio** [comment]
I personally don't think it should be addressed by this plugin. It would make more sense if Obsidian would add an option to enable markdown rendering (in general, not only inline math) inside code blocks or someone would created a new plugin that does that.
